Bluron: backup/openmp/src/GameOfLife_Test.cpp File Reference
GameOfLife_Test.cpp File Reference
#include "GameOfLife.h"
#include "GameOfLife.cpp"
#include <gtest/gtest.h>
Functions
TEST (SquareRootTest, PositiveNos)
TEST (SquareRootTest, NegativeNos)
TEST (CountNeighBoursTest, CountNear)
TEST (GetStatusElement, NoNeighbours)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 54 of file GameOfLife_Test.cpp.
 {
     testing::InitGoogleTest(&argc, argv);
     return RUN_ALL_TESTS();
 }
TEST() [1/4]
TEST (CountNeighBoursTest , CountNear)
Definition at line 21 of file GameOfLife_Test.cpp.
{
     GameOfLife *game;
     game = new GameOfLife(512,512);
     game->randomInit();
     game->setElement(0,0, false);
     game->setElement(0,1, false);
     game->setElement(0,2, true);
     game->setElement(1,0, false);
     game->setElement(1,1, false);
     game->setElement(1,2, true);
     game->setElement(2,0, false);
     game->setElement(2,1, false);
     game->setElement(2,2, true);
     bool countElement = game->countNeighbors(1,1);
     printf("countElement: %i", countElement);
     ASSERT_EQ(4.0, countElement);
 }
References GameOfLife::countNeighbors(), game, GameOfLife::randomInit(), and GameOfLife::setElement().
TEST() [2/4]
TEST (GetStatusElement , NoNeighbours)
Definition at line 43 of file GameOfLife_Test.cpp.
 {
     GameOfLife *game;
     game = new GameOfLife(512,512);
     game->randomInit();
     game->setElement(1,1, true);
     bool element = game->getElement(1,1);
     ASSERT_EQ(true, element);
     // check lengt of array grid
 }
References game, GameOfLife::getElement(), GameOfLife::randomInit(), and GameOfLife::setElement().
TEST() [3/4]
TEST (SquareRootTest , NegativeNos)
Definition at line 15 of file GameOfLife_Test.cpp.
 {
     ASSERT_EQ(-1.0, squareRoot(-15.0));
     ASSERT_EQ(-1.0, squareRoot(-0.2));
 }
References squareRoot().
TEST() [4/4]
TEST (SquareRootTest , PositiveNos)
Definition at line 7 of file GameOfLife_Test.cpp.
 {
     ASSERT_EQ(6, squareRoot(36.0));
     ASSERT_EQ(18, squareRoot(324.0));
     ASSERT_EQ(25.4, squareRoot(645.16));
     ASSERT_EQ(0, squareRoot(0.0));
 }
References squareRoot().