Bluron: opencl/gol.cpp File Reference
gol.cpp File Reference
#include <iostream>
#include <fstream>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <time.h>
#include <omp.h>
#include <GL/glew.h>
#include <CL/opencl.h>
#include <GL/freeglut.h>
#include <GL/glx.h>
Macros
#define CL_TARGET_OPENCL_VERSION 110
A opencl class.
Functions
void initGL (int argc, char *argv[])
binding rendered_texture to image in opencl , for the display
void startGL ()
run 2 call back function one for display , one for copy output to opengl, reshape function
void displayTimer (int value)
glutPostRedisplay containts in this function
void generationTimer (int value)
glutPostRedisplay containts in this function
void display ()
glutPostRedisplay containts in this function
void mouse (int button, int state, int x, int y)
mouse scroll up and down to view
void specialKeys (int key, int x, int y)
specialKeys with keyboar
void reshape (GLsizei width, GLsizei height)
reshape view
int loadProgramSource (const char *filename, char **p_source_string, size_t *length)
A Load function .
void clean ()
A function .
void die (cl_int err, const char *str)
void golMapRandFill ()
A function.
int main (int argc, char *argv[])
Variables
int sample_rate = 100000
GLfloat angle = 0.0f
int refresh_mills = 1000.0/30.0
bool full_screen_mode = false
refresh interval in milliseconds
char title [] = "Game of Life on OpenCL (faster than openMP)"
int window_width = 512
int window_height = 512
Windowed mode's width.
int window_pos_x = 50
Windowed mode's height.
int window_pos_y = 50
Windowed mode's top-left corner x.
double zoom = 1.0
Windowed mode's top-left corner y.
double ortho_left = -1.0
double ortho_right = 1.0
double ortho_top = 1.0
double ortho_bottom = -1.0
clock_t wall_clock = 0
GLuint frame_buffer_name = 0
GLuint rendered_texture
GLuint rendered_texture_out
const char * kernel_source = "opencl/devGolGenerateShr.cl"
char * source_string = NULL
cl_context_properties properties [7]
cl_context context
cl_command_queue command_quque
cl_platform_id platform
cl_device_id device
cl_program program
cl_kernel kernel
cl_mem dev_gol_map_in
cl_mem dev_gol_map_out
cl_mem dev_gol_image
size_t size
clGetGLContextInfoKHR_fn myGetGLContextInfoKHR
size_t elements_size [2]
size_t global_work_size [2]
size_t local_work_size [2]
size_t param_data_bytes
size_t kernel_length
size_t build_log_size_ret
cl_int err
char * build_log
char * gol_map = NULL
char * gol_tmap = NULL
int gol_map_width = 512
int gol_map_height = 512
long long int gol_generation = 0
Macro Definition Documentation
CL_TARGET_OPENCL_VERSION
#define CL_TARGET_OPENCL_VERSION 110
A opencl class.
A test class for game of life how to install : https://www.srcmake.com/home/google-cpp-test-framework document at https://google.github.io/googletest/ reference: https://github.com/mbdriscoll/examples/blob/master/clgl_interop/example.c example with glCreateFromOpenGLBuffer
Definition at line 15 of file gol.cpp.
Function Documentation
clean()
void clean ()
A function .
free variable after finish
Definition at line 263 of file gol.cpp.
 {
     if(source_string) free(source_string);
     if(kernel) free(kernel);
     if(program) free(program);
     if(command_quque) free(command_quque);
     if(context) free(context);
     if(device) free(device);
     if(platform) free(platform);
     if(dev_gol_map_in) free(dev_gol_map_in);
     if(dev_gol_map_out) free(dev_gol_map_out);
     free(gol_map);
     free(gol_tmap);
 }
References command_quque, context, dev_gol_map_in, dev_gol_map_out, device, gol_map, gol_tmap, kernel, platform, program, and source_string.
die()
void die (cl_int err, const char * str)
! print error if error
Definition at line 249 of file gol.cpp.
 {
     if(err != CL_SUCCESS)
     {
         fprintf(stderr, "Error code %d: %s\n", err, str);
         clean();
         exit(1);
     }
 }
References clean(), and err.
display()
void display ()
glutPostRedisplay containts in this function
A function .
call backfunction generationTimer and realease : dev_gol_image
Definition at line 412 of file gol.cpp.
 {
     glClear(GL_COLOR_BUFFER_BIT);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glOrtho(ortho_left, ortho_right, ortho_bottom, ortho_top, -10, 10);
     glScalef(zoom, zoom, 1.0);
     glEnable(GL_TEXTURE_2D);
     glTexImage2D(GL_TEXTURE_2D, 0, GL_LUMINANCE, gol_map_width, gol_map_height, 0, GL_LUMINANCE, GL_UNSIGNED_BYTE, gol_map);
     // glTexImage2D(GL_TEXTURE_2D, 0, GL_LUMINANCE, gol_map_width, gol_map_height, 0, GL_LUMINANCE, GL_UNSIGNED_BYTE, gol_map);
     // glTexImage2D :  declares a textures size, color components (RGBA, etc), datatype (byte, float...), pixel data,
     glBindTexture(GL_TEXTURE_2D, rendered_texture);
     // bind the given texture to the active store. Only one
     // texture can be bound at a time. All future configuration and
     // co-ordinates correspond to this texture.
     glBegin(GL_QUADS);
         glTexCoord2f(0.0, 0.0); glVertex3f(-1.0, -1.0, 0.0);
         glTexCoord2f(1.0, 0.0); glVertex3f( 1.0, -1.0, 0.0);
         glTexCoord2f(1.0, 1.0); glVertex3f( 1.0,  1.0, 0.0);
         glTexCoord2f(0.0, 1.0); glVertex3f(-1.0,  1.0, 0.0);
     glEnd();
     glutSwapBuffers();
 }
References gol_map, gol_map_height, gol_map_width, ortho_bottom, ortho_left, ortho_right, ortho_top, rendered_texture, and zoom.
displayTimer()
void displayTimer (int value)
glutPostRedisplay containts in this function
A init function .
call backfunction glutPostRedisplay
Definition at line 362 of file gol.cpp.
 {
     glutPostRedisplay();
     glutTimerFunc(refresh_mills, displayTimer, 0);
 }
References displayTimer(), and refresh_mills.
generationTimer()
void generationTimer (int value)
glutPostRedisplay containts in this function
A function .
call backfunction generationTimer and realease : dev_gol_image
Definition at line 372 of file gol.cpp.
 {
     err = clEnqueueAcquireGLObjects(command_quque, 1, &dev_gol_image, 0, 0, 0);
     die(err, "clEnqueueAcquireGLObjects");
     //err  = clEnqueueWriteBuffer(command_quque, dev_gol_map_in, CL_FALSE, 0, sizeof(cl_char) * global_work_size[0] * global_work_size[1] , gol_map, 0, NULL, NULL);
     //die(err, "clEnqueueWriteBuffer");
     clEnqueueNDRangeKernel(command_quque, kernel, 2, NULL, global_work_size, local_work_size, 0, NULL, NULL);
     die(err, "clEnqueueNDRangeKernel");
     //err = clEnqueueReadBuffer(command_quque, dev_gol_map_out, CL_TRUE, 0, sizeof(cl_char) * global_work_size[0] * global_work_size[1] , gol_tmap, 0, NULL, NULL);
     //die(err, "clEnqueueReadBuffer");
     clFinish(command_quque);
     err = clEnqueueCopyBuffer(command_quque, dev_gol_map_out, dev_gol_map_in, 0, 0, sizeof(unsigned char) * global_work_size[0] * global_work_size[1], 0, NULL, NULL);
     die(err, "clEnqueueCopyBuffer");
     err = clEnqueueReleaseGLObjects(command_quque, 1,  &dev_gol_image, 0, 0, NULL);
     die(err, "clEnqueueReleaseGLObjects");
     //memcpy(gol_map, gol_tmap, sizeof(cl_char) * global_work_size[0] * global_work_size[1]);
     // std::cout << &dev_gol_image;
     gol_generation++;
     if(gol_generation % sample_rate == 0){
         clock_t now = clock();
         double fps = (double)sample_rate / ( (now - wall_clock) / CLOCKS_PER_SEC );
         printf("generation : %lli\n", gol_generation);
         printf("fps = %lf\n", fps);
         wall_clock = now;
     }
     glutTimerFunc(0, generationTimer, 0);
 }
References command_quque, dev_gol_image, dev_gol_map_in, dev_gol_map_out, die(), err, generationTimer(), global_work_size, gol_generation, kernel, local_work_size, sample_rate, and wall_clock.
golMapRandFill()
void golMapRandFill ()
A function.
! game functions, generate gird with 2 for loop
using randome to create te grid in the game of life
Definition at line 574 of file gol.cpp.
 {
     unsigned seed = time(0);
     //#pragma omp parallel firstprivate(seed)
     //{
         srand(seed);
         //seed = omp_get_thread_num();
         //#pragma omp for collapse(2)
         for(int j=0; j<gol_map_width; ++j)
         {
             for(int i=0; i<gol_map_height; ++i)
             {
                 gol_map[i*gol_map_width+j] = (rand() & 0x1);
             }
         }
     //}
 }
References gol_map, gol_map_height, and gol_map_width.
initGL()
void initGL (int argc, char * argv[])
binding rendered_texture to image in opencl , for the display
A init function .
Init function
init OpenGL with glBindTexture and variable : rendered_texture
Definition at line 317 of file gol.cpp.
 {
     glutInit(&argc, argv);
     glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGBA);
     glutInitWindowSize(window_width, window_height);
     glutInitWindowPosition(window_pos_x, window_pos_y);
     glutCreateWindow(title);
     glutDisplayFunc(display);
     glutReshapeFunc(reshape);
     glutSpecialFunc(specialKeys); // Register callback handler for special-key event
     glutMouseFunc(mouse);
     glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
     /*
     //framebuffer
     glGenFramebuffers(1, &frame_buffer_name);
     glBindFramebuffer(GL_FRAMEBUFFER, frame_buffer_name);
 */
     glGenTextures(1, &rendered_texture);
     glBindTexture(GL_TEXTURE_2D, rendered_texture);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
     glTexImage2D(GL_TEXTURE_2D, 0, GL_LUMINANCE, gol_map_width, gol_map_height, 0, GL_LUMINANCE, GL_UNSIGNED_BYTE, 0);
     glFinish();
 }
References display(), gol_map_height, gol_map_width, mouse(), rendered_texture, reshape(), specialKeys(), title, window_height, window_pos_x, window_pos_y, and window_width.
loadProgramSource()
int loadProgramSource (const char * filename, char ** p_source_string, size_t * length)
A Load function .
Load file kern for opencl
Definition at line 283 of file gol.cpp.
 {
     FILE *file;
     size_t source_length;
     file = fopen(filename, "rb");
     if(file == 0)
     {
         return 1;
     }
     fseek(file, 0, SEEK_END);
     source_length = ftell(file);
     fseek(file, 0, SEEK_SET);
     *p_source_string = (char *)malloc(source_length + 1);
     if(fread(*p_source_string, source_length, 1, file) != 1)
     {
         fclose(file);
         free(*p_source_string);
         return 1;
     }
     fclose(file);
     *length = source_length;
     (*p_source_string)[source_length] = '\0';
     return 0;
 }
main()
int main (int argc, char * argv[])
! allocate host memory
! init gol_map
! end init gol_map
! create buffers
cai nay loi dev_gol_image = clCreateFromGLBuffer(context, CL_MEM_WRITE_ONLY, rendered_texture, &err);
Definition at line 123 of file gol.cpp.
 {
     initGL(argc, argv);
     elements_size[0] = gol_map_width; //cell slots
     elements_size[1] = gol_map_height; //cell slots
     local_work_size[0] = 32;
     local_work_size[1] = 32;
     global_work_size[0] = (size_t)ceil((double)elements_size[0] / local_work_size[0]) * local_work_size[0];
     global_work_size[1] = (size_t)ceil((double)elements_size[1] / local_work_size[1]) * local_work_size[1];
     printf("global_work_size[0]=%lu, local_work_size[0]=%lu, elements_size[0]=%lu, work_groups_x=%lu\n",
             global_work_size[0], local_work_size[0], elements_size[0], global_work_size[0] / local_work_size[0]);
     printf("global_work_size[1]=%lu, local_work_size[1]=%lu, elements_size[1]=%lu, work_groups_y=%lu\n",
             global_work_size[1], local_work_size[1], elements_size[1], global_work_size[1] / local_work_size[1]);
     gol_map      = (char *)malloc(sizeof(cl_char) * global_work_size[0] * global_work_size[1]);
     gol_tmap     = (char *)malloc(sizeof(cl_char) * global_work_size[0] * global_work_size[1]);
     /* end allocate host memory */
     golMapRandFill();
     err = clGetPlatformIDs(1, &platform, NULL);
     die(err, "clGetPlatformIds");
     /*
     err = clGetDeviceIDs(platform, CL_DEVICE_TYPE_GPU, 1, &device, NULL);
     die(err, "clGetDeviceIDs");
     */
     /*
     context = clCreateContext(0, 1, &device, NULL, NULL, &err);
     die(err, "clCreateContext");
     */
     properties[0] = CL_GL_CONTEXT_KHR;  properties[1] = (cl_context_properties)glXGetCurrentContext();
     properties[2] = CL_GLX_DISPLAY_KHR; properties[3] = (cl_context_properties)glXGetCurrentDisplay();
     properties[4] = CL_CONTEXT_PLATFORM;  properties[5] = (cl_context_properties)platform;
     properties[6] = 0;
     myGetGLContextInfoKHR = (clGetGLContextInfoKHR_fn)clGetExtensionFunctionAddress("clGetGLContextInfoKHR");
     myGetGLContextInfoKHR(properties, CL_DEVICES_FOR_GL_CONTEXT_KHR, sizeof(cl_device_id), &device, &size);
     context =  clCreateContext(properties, 1, &device, NULL, NULL, &err);
     die(err, "clCreateContext");
     //printf("dev=%lu, ctx=%lu\n", device, context);
     command_quque = clCreateCommandQueue(context, device, 0, &err);
     die(err, "clCreateCommandQueue");
     // https://software.intel.com/content/www/us/en/develop/articles/opencl-and-opengl-interoperability-tutorial.html?fbclid=IwAR2oqBm5aDz-owEuqlG-GOSMv04-Dkp1sYSzEt3PZkFTSj6paL9BERnE3Ik
     // OpenGL texture (or render-buffer) becomes an OpenCL image (via clCreateFromGLTexture).
     //  clCreateFromGLTexture2D: Creates an OpenCL image object from the OpenGL texture object , CL_MEM_WRITE_ONLY for faster discarding data
     dev_gol_image = clCreateFromGLTexture2D(context, CL_MEM_WRITE_ONLY, GL_TEXTURE_2D, 0, rendered_texture, &err);
         die(err, "clCreateBuffer dev_gol_image");
     dev_gol_map_in = clCreateBuffer(context, CL_MEM_READ_WRITE, sizeof(cl_char) * global_work_size[0] * global_work_size[1] , NULL, &err);
     die(err, "clCreateBuffer dev_gol_map_in");
     dev_gol_map_out = clCreateBuffer(context, CL_MEM_READ_WRITE, sizeof(cl_char) * global_work_size[0] * global_work_size[1], NULL, &err);
     die(err, "clCreateBuffer dev_gol_map_out");
     /* end create buffers */
     loadProgramSource(kernel_source, &source_string, &kernel_length);
     program = clCreateProgramWithSource(context, 1, (const char **)&source_string, &kernel_length, &err);
     die(err, "clCreateProgramWithSource");
     err = clBuildProgram(program, 0, NULL, NULL, NULL, NULL);
     if(err != CL_SUCCESS)
     {
         err = clGetProgramBuildInfo(program, device, CL_PROGRAM_BUILD_LOG, 0, NULL, &build_log_size_ret);
         build_log = (char *)malloc(build_log_size_ret);
         err = clGetProgramBuildInfo(program, device, CL_PROGRAM_BUILD_LOG, build_log_size_ret, build_log, NULL);
         printf("%s\n", build_log);
         exit(1);
     }
     //die(err, "clBuildProgram");
     kernel = clCreateKernel(program, "devGolGenerate", &err);
     die(err, "clCreateKernel devGolGenerate");
     err  = clSetKernelArg(kernel, 0, sizeof(cl_mem), (void *)&dev_gol_map_in);
     die(err, "clSetKernelArg 0");
     err  = clSetKernelArg(kernel, 1, sizeof(cl_mem), (void *)&dev_gol_map_out);
     die(err, "clSetKernelArg 1");
     err  = clSetKernelArg(kernel, 2, sizeof(cl_mem), (void *)&dev_gol_image);
     die(err, "clSetKernelArg 1");
     err  = clSetKernelArg(kernel, 3, sizeof(cl_int), (void *)&elements_size[0]);
     die(err, "clSetKernelArg 3");
     err  = clSetKernelArg(kernel, 4, sizeof(cl_int), (void *)&elements_size[1]);
     die(err, "clSetKernelArg 4");
     // copy data to input
     err  = clEnqueueWriteBuffer(command_quque, dev_gol_map_in, CL_FALSE, 0, sizeof(cl_char) * global_work_size[0] * global_work_size[1] , gol_map, 0, NULL, NULL);
     die(err, "clEnqueueWriteBuffer");
     // for (size_t i = 0; i < gol_map_width; i++)
     // {
     //     for (size_t j = 0; j < gol_map_height; j++)
     //     {
     //         std::cout << gol_map;
     //     }
     // }
     startGL();
     /* output result */
     clean();
     return 0;
 }
References build_log, build_log_size_ret, clean(), command_quque, context, dev_gol_image, dev_gol_map_in, dev_gol_map_out, device, die(), elements_size, err, global_work_size, gol_map, gol_map_height, gol_map_width, gol_tmap, golMapRandFill(), initGL(), kernel, kernel_length, kernel_source, loadProgramSource(), local_work_size, myGetGLContextInfoKHR, platform, program, properties, rendered_texture, size, source_string, and startGL().
mouse()
void mouse (int button, int state, int x, int y)
mouse scroll up and down to view
A function.
mouse click
Definition at line 445 of file gol.cpp.
 {
     // Wheel reports as button 3(scroll up) and button 4(scroll down)
     if ((button == 3) || (button == 4)) // It's a wheel event
     {
         // Each wheel event reports like a button click, GLUT_DOWN then GLUT_UP
         if (state == GLUT_UP) return; // Disregard redundant GLUT_UP events
         //printf("Scroll %s At %d %d\n", (button == 3) ? "Up" : "Down", x, y);
         if(button == 3)
             zoom += 0.1;
         else
             zoom -= 0.1;
         if(zoom < 0) zoom = 0.1;
         GLfloat aspect = (GLfloat)window_width / (GLfloat)window_height;
         if(window_width >= window_height)
         {
             ortho_left = (GLfloat)x / window_width - 2.0 / zoom;
             ortho_right = (GLfloat)x / window_width + 2.0 / zoom;
             ortho_top = (GLfloat)y / window_height / aspect + 2.0 / zoom;
             ortho_bottom = (GLfloat)y / window_height / aspect - 2.0 / zoom;
         }
         else
         {
             ortho_left = (GLfloat)x / window_width * aspect - 2.0 / zoom;
             ortho_right = (GLfloat)x / window_width * aspect + 2.0 / zoom;
             ortho_top = (GLfloat)y / window_height + 2.0 / zoom;
             ortho_bottom = (GLfloat)y / window_height - 2.0 / zoom;
         }
     }else{  // normal button event
         //printf("Button %s At %d %d\n", (state == GLUT_DOWN) ? "Down" : "Up", x, y);
     }
 }
References ortho_bottom, ortho_left, ortho_right, ortho_top, window_height, window_width, and zoom.
reshape()
void reshape (GLsizei width, GLsizei height)
reshape view
A function.
reshape function in opengl
Definition at line 518 of file gol.cpp.
 {
     // Compute aspect ratio of the new window
     if (height == 0) height = 1;                // To prevent divide by 0
     GLfloat aspect = (GLfloat)width / (GLfloat)height;
     // Set the viewport to cover the new window
     glViewport(0, 0, width, height);
     // Set the aspect ratio of the clipping area to match the viewport
     glMatrixMode(GL_PROJECTION);  // To operate on the Projection matrix
     glLoadIdentity();             // Reset the projection matrix
     if (width >= height) {
         // aspect >= 1, set the height from -1 to 1, with larger width
         gluOrtho2D(-1.0 * aspect, 1.0 * aspect, -1.0, 1.0);
     } else {
         // aspect < 1, set the width to -1 to 1, with larger height
         gluOrtho2D(-1.0, 1.0, -1.0 / aspect, 1.0 / aspect);
         // gluOrtho2D(ortho_left, ortho_right, ortho_bottom, ortho_top);
     }
 }
specialKeys()
void specialKeys (int key, int x, int y)
specialKeys with keyboar
A function.
mouse specialKeys
Definition at line 487 of file gol.cpp.
{
     switch (key) {
         case GLUT_KEY_F1:    // F1: Toggle between full-screen and windowed mode
             full_screen_mode = !full_screen_mode;         // Toggle state
             if (full_screen_mode) {                     // Full-screen mode
                 window_pos_x   = glutGet(GLUT_WINDOW_X); // Save parameters for restoring later
                 window_pos_y   = glutGet(GLUT_WINDOW_Y);
                 window_width  = glutGet(GLUT_WINDOW_WIDTH);
                 window_height = glutGet(GLUT_WINDOW_HEIGHT);
                 glutFullScreen();                      // Switch into full screen
             } else {                                         // Windowed mode
                 glutReshapeWindow(window_width, window_height); // Switch into windowed mode
                 glutPositionWindow(window_pos_x, window_pos_y);   // Position top-left corner
             }
             break;
         case GLUT_KEY_HOME:
             ortho_left = ortho_top = 1.0;
             ortho_right = ortho_bottom = -1.0;
             zoom = 1.0;
             glutPostRedisplay();
             break;
         case GLUT_KEY_END:
             glutLeaveMainLoop();
             break;
     }
 }
References full_screen_mode, ortho_bottom, ortho_left, ortho_right, ortho_top, window_height, window_pos_x, window_pos_y, window_width, and zoom.
startGL()
void startGL ()
run 2 call back function one for display , one for copy output to opengl, reshape function
A init function .
startGL caculate after init
Definition at line 351 of file gol.cpp.
 {
     glutTimerFunc(0, displayTimer, 0);
     glutTimerFunc(0, generationTimer, 0);
     glutMainLoop();
 }
References displayTimer(), and generationTimer().
Variable Documentation
angle
GLfloat angle = 0.0f
Definition at line 25 of file gol.cpp.
build_log
char* build_log
Definition at line 97 of file gol.cpp.
build_log_size_ret
size_t build_log_size_ret
Definition at line 93 of file gol.cpp.
command_quque
cl_command_queue command_quque
Definition at line 75 of file gol.cpp.
context
cl_context context
Definition at line 74 of file gol.cpp.
dev_gol_image
cl_mem dev_gol_image
Definition at line 82 of file gol.cpp.
dev_gol_map_in
cl_mem dev_gol_map_in
Definition at line 80 of file gol.cpp.
dev_gol_map_out
cl_mem dev_gol_map_out
Definition at line 81 of file gol.cpp.
device
cl_device_id device
Definition at line 77 of file gol.cpp.
elements_size
size_t elements_size[2]
Definition at line 88 of file gol.cpp.
err
cl_int err
Definition at line 96 of file gol.cpp.
frame_buffer_name
GLuint frame_buffer_name = 0
Definition at line 40 of file gol.cpp.
full_screen_mode
bool full_screen_mode = false
refresh interval in milliseconds
Definition at line 27 of file gol.cpp.
global_work_size
size_t global_work_size[2]
Definition at line 89 of file gol.cpp.
gol_generation
long long int gol_generation = 0
Definition at line 108 of file gol.cpp.
gol_map
char* gol_map = NULL
Definition at line 105 of file gol.cpp.
gol_map_height
int gol_map_height = 512
Definition at line 107 of file gol.cpp.
gol_map_width
int gol_map_width = 512
Definition at line 106 of file gol.cpp.
gol_tmap
char * gol_tmap = NULL
Definition at line 105 of file gol.cpp.
kernel
cl_kernel kernel
Definition at line 79 of file gol.cpp.
kernel_length
size_t kernel_length
Definition at line 92 of file gol.cpp.
kernel_source
const char* kernel_source = "opencl/devGolGenerateShr.cl"
Definition at line 69 of file gol.cpp.
local_work_size
size_t local_work_size[2]
Definition at line 90 of file gol.cpp.
myGetGLContextInfoKHR
clGetGLContextInfoKHR_fn myGetGLContextInfoKHR
Definition at line 85 of file gol.cpp.
ortho_bottom
double ortho_bottom = -1.0
Definition at line 37 of file gol.cpp.
ortho_left
double ortho_left = -1.0
Definition at line 34 of file gol.cpp.
ortho_right
double ortho_right = 1.0
Definition at line 35 of file gol.cpp.
ortho_top
double ortho_top = 1.0
Definition at line 36 of file gol.cpp.
param_data_bytes
size_t param_data_bytes
Definition at line 91 of file gol.cpp.
platform
cl_platform_id platform
Definition at line 76 of file gol.cpp.
program
cl_program program
Definition at line 78 of file gol.cpp.
properties
cl_context_properties properties[7]
Definition at line 73 of file gol.cpp.
refresh_mills
int refresh_mills = 1000.0/30.0
Definition at line 26 of file gol.cpp.
rendered_texture
GLuint rendered_texture
Definition at line 41 of file gol.cpp.
rendered_texture_out
GLuint rendered_texture_out
Definition at line 41 of file gol.cpp.
sample_rate
int sample_rate = 100000
Definition at line 22 of file gol.cpp.
size
size_t size
Definition at line 83 of file gol.cpp.
source_string
char* source_string = NULL
Definition at line 70 of file gol.cpp.
title
char title[] = "Game of Life on OpenCL (faster than openMP)"
Definition at line 28 of file gol.cpp.
wall_clock
clock_t wall_clock = 0
Definition at line 38 of file gol.cpp.
window_height
int window_height = 512
Windowed mode's width.
Definition at line 30 of file gol.cpp.
window_pos_x
int window_pos_x = 50
Windowed mode's height.
Definition at line 31 of file gol.cpp.
window_pos_y
int window_pos_y = 50
Windowed mode's top-left corner x.
Definition at line 32 of file gol.cpp.
window_width
int window_width = 512
Definition at line 29 of file gol.cpp.
zoom
double zoom = 1.0
Windowed mode's top-left corner y.
Definition at line 33 of file gol.cpp.